name: JAVA CI with Gradle

on:
  workflow_dispatch:
#  push :
#    branches: ["main"]

permissions:
  content: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. JAVA 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        whit:
          java-version: '17'
          distribution: 'temurin'

      # 2. Gradle 설정
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      # 3. Gradle Wrapper에 실행 권한을 부여
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      # 4. Spring Boot 애플리케이션 빌드
      - name: Build specific module
        run: cd softdelete && ../gradlew clean bootJar
      # 5. Docker 이미지 빌드
      - name: Docker image build
        run: docker build -f softdelete/Dockerfile.spring -t ${{ secrets.DOCKER_USERNAME }}/spring-demo .

      # 6. Docker
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      # 7. Docker 이미지 푸시
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-demo