name: JAVA CI\CD with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. JAVA 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 2. Gradle 설정
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      # 3. Gradle Wrapper에 실행 권한을 부여
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      # 4. Spring Boot 애플리케이션 빌드
      - name: Build specific module
        run: cd softdelete && ../gradlew clean bootJar
      # 5. Docker 이미지 빌드
      - name: Docker image build
        run: docker build -f softdelete/Dockerfile.spring -t ${{ secrets.DOCKER_USERNAME }}/spring-demo .

      # 6. Docker 이미지 빌드 (Fluentd)
      - name: Build Fluentd Docker image
        run: docker build -f softdelete/Dockerfile.fluentd -t ${{ secrets.DOCKER_USERNAME }}/fluentd-demo softdelete

      # 6. Docker
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      # 7. Docker 이미지 푸시
      - name: Push Spring Boot Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-demo

      - name: Push Fluentd Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fluentd-demo

  deploy:
    needs: build-docker-image
    runs-on: self-hosted
    steps:
      - name: s3 file download 1
        run: |
          # 만약 파일이 있다면 최신화를 위해서 삭제
            if [ -f /home/ec2-user/.env ]; then
              echo "File already exists. Deleting the old file."
              rm /home/ec2-user/.env
            fi
          
            # AWS CLI로 S3에서 파일 다운로드
            aws s3 cp s3://cicd-bucket-1004/.env /home/ec2-user/.env

      - name: s3 file download 2
        run: |
          if [ -f /home/ec2-user/docker-compose.yml ]; then
            echo "File already exists. Deleting the old file."
            rm /home/ec2-user/docker-compose.yml
          fi
          
          # AWS CLI로 S3에서 파일 다운로드
          aws s3 cp s3://cicd-bucket-1004/docker-compose.yml /home/ec2-user/docker-compose.yml


      - name: docker compose 사용
        run: |
          sudo docker-compose up -d